# Please Build file for the channel_example Go module.
# Author: Andrew Jarombek
# Date: 9/18/2022

go_binary(
    name = "binary",
    srcs = ["channel_example.go"],
    out = "channel_example",
    deps = ["//:go_download"],
    labels = [
        "goroutines",
        "binary",
    ],
)