# Please Build file for the goroutine_example Go module.
# Author: Andrew Jarombek
# Date: 9/18/2022

go_binary(
    name = "binary",
    srcs = ["goroutine_example.go"],
    out = "goroutine_example",
    deps = ["//:go_download"],
    labels = [
        "goroutines",
        "binary",
    ],
)