# Please Build file for the reflection Go module.
# Author: Andrew Jarombek
# Date: 9/17/2022

go_test(
    name = "test",
    srcs = [
        "basics_test.go",
        "map_test.go"
    ],
    deps = [
        "//:go_download",
        "//:testify",
    ],
    labels = [
        "reflection",
        "test"
    ],
)