# GitHub Action for linting and formatting Go code
# Author: Andrew Jarombek
# Date: 11/13/2022

name: Go Lint and Format

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    container: ajarombek/go-alpine-linux-programming:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Run golint
        run: golint ./...

      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports

      - name: Run goimports
        run: goimports -l -w .

      - name: Check for changes after goimports
        run: |
          git diff --exit-code || { echo "Please run goimports to format the code."; exit 1; }

      - name: Install golangci-lint
        run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Run golangci-lint
        run: golangci-lint run
